version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: social_network_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://user:password@db/social_network_db

volumes:
  postgres_data:
